version: "3"
services:
  seq:
    image: datalust/seq:latest
    ports:
      - ${SEQ_PORT:-5341}:80
    volumes:
      - ./data/seq:/data
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - edgeiot

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - 25:1025
      - 8025:8025
    networks:
      - edgeiot

  azurite:
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./data/azurite:/data
    image: mcr.microsoft.com/azure-storage/azurite
    networks:
      - edgeiot

networks:
  edgeiot:
