services:
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - tanbyiot

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - 25:1025
      - 8025:8025
    networks:
      - tanbyiot

  postgres:
    ports:
      - "5432:5432"
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=SekretPassword!
    networks:
      - tanbyiot

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - tanbyiot

networks:
  tanbyiot:
