# Build
FROM node:16-alpine AS build
WORKDIR /app
COPY ./src/edgeiot.client .
RUN npm install
RUN npm run build

# Runtime
FROM nginx:alpine
COPY --from=build app/dist /usr/share/nginx/html
COPY _build/client.nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


